In [1]:
# Import pandas
# Create a series of fruits(string) of length 5 and view it
import pandas as pd
d=pd.Series(['Apple','Mango','Strawberry','Orange','Grapes'])
d

0         Apple
1         Mango
2    Strawberry
3        Orange
4        Grapes
dtype: object

In [2]:
# Create a series of prices(int) of length 5 and view it
s=pd.Series([100,120,150,50,70])
s

0    100
1    120
2    150
3     50
4     70
dtype: int64

In [3]:
# Create a fruit_prices dataframe out of the 2 series you just made and view it
fruit_prices={
    'Fruit':['Apple','Mango','Strawberry','Orange','Grapes'],
    'Price':[100,120,150,50,70]
}
df=pd.DataFrame(fruit_prices)
df

        Fruit  Price
0       Apple    100
1       Mango    120
2  Strawberry    150
3      Orange     50
4      Grapes     70

In [4]:
import numpy as np
# Find the mean, sum, standard deviation, variance of the prices
d=np.array(df['Price'])
print('mean:',d.mean());print('Sum:',d.sum())
print('std deviation:',d.std());print('Variance:',d.std()**2)

mean: 98.0
Sum: 490
std deviation: 35.4400902933387
Variance: 1255.9999999999998

In [5]:
# import the csv file given to you and turn it into a DataFrame
cereal=pd.read_csv("cereal.csv")
print(cereal.dtypes)

name         object
mfr          object
type         object
calories      int64
protein       int64
fat           int64
sodium        int64
fiber       float64
carbo       float64
sugars        int64
potass        int64
vitamins      int64
shelf         int64
weight      float64
cups        float64
rating      float64
dtype: object

In [6]:
# Describe your current DataFrame using describe()
cereal.describe()

,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
count,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000,77.000000
mean,106.883117,2.545455,1.012987,159.675325,2.151948,14.597403,6.922078,96.077922,28.246753,2.207792,1.029610,0.821039,42.665705
std,19.484119,1.094790,1.006473,83.832295,2.383364,4.278956,4.444885,71.286813,22.342523,0.832524,0.150477,0.232716,14.047289
min,50.000000,1.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000,1.000000,0.500000,0.250000,18.042851
25%,100.000000,2.000000,0.000000,130.000000,1.000000,12.000000,3.000000,40.000000,25.000000,1.000000,1.000000,0.670000,33.174094
50%,110.000000,3.000000,1.000000,180.000000,2.000000,14.000000,7.000000,90.000000,25.000000,2.000000,1.000000,0.750000,40.400208
75%,110.000000,3.000000,2.000000,210.000000,3.000000,17.000000,11.000000,120.000000,25.000000,3.000000,1.000000,1.000000,50.828392
max,160.000000,6.000000,5.000000,320.000000,14.000000,23.000000,15.000000,330.000000,100.000000,3.000000,1.500000,1.500000,93.704912

In [7]:
# Get information about your DataFrame using info()
cereal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      77 non-null     object
 1   mfr       77 non-null     object
 2   type      77 non-null     object
 3   calories  77 non-null     int64
 4   protein   77 non-null     int64
 5   fat       77 non-null     int64
 6   sodium    77 non-null     int64
 7   fiber     77 non-null     float64
 8   carbo     77 non-null     float64
 9   sugars    77 non-null     int64
 10  potass    77 non-null     int64
 11  vitamins  77 non-null     int64
 12  shelf     77 non-null     int64
 13  weight    77 non-null     float64
 14  cups      77 non-null     float64
 15  rating    77 non-null     float64
dtypes: float64(5), int64(8), object(3)
memory usage: 9.8+ KB

In [8]:
# Find the length of the DataFrame
cereal.size

1232

In [9]:
# Find the unique values in shelf column
cereal.shelf.unique()

array([3, 1, 2], dtype=int64)

In [10]:
# Show the first 7 rows of the DataFrame
cereal.head(7)

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843
5,Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1.0,0.75,29.509541
6,Apple Jacks,K,C,110,2,0,125,1.0,11.0,14,30,25,2,1.0,1.00,33.174094

In [11]:
# Show the last 7 rows of the DataFrame
cereal.tail(7)

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
70,Total Raisin Bran,G,C,140,3,1,190,4.0,15.0,14,230,100,3,1.5,1.00,28.592785
71,Total Whole Grain,G,C,100,3,1,200,3.0,16.0,3,110,100,3,1.0,1.00,46.658844
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559

In [12]:
# Use .loc to find the sodium value of the 4th item
print(cereal.loc[4,'sodium']);print()

200

In [13]:
# Use .iloc to find the value of the 7th row and 7th column
cereal.iloc[7]

name        Basic 4
mfr               G
type              C
calories        130
protein           3
fat               2
sodium          210
fiber             2
carbo            18
sugars            8
potass          100
vitamins         25
shelf             3
weight         1.33
cups           0.75
rating      37.0386
Name: 7, dtype: object

In [14]:
cereal.iloc[:,7]

0     10.0
1      2.0
2      9.0
3     14.0
4      1.0
      ...
72     0.0
73     0.0
74     3.0
75     3.0
76     1.0
Name: fiber, Length: 77, dtype: float64

In [15]:
# Select the \"name\" column from the DataFrame
cereal['name']

0                     100% Bran
1             100% Natural Bran
2                      All-Bran
3     All-Bran with Extra Fiber
4                Almond Delight
                ...
72                      Triples
73                         Trix
74                   Wheat Chex
75                     Wheaties
76          Wheaties Honey Gold
Name: name, Length: 77, dtype: object

In [16]:
# Select the rows which have more than 100 calories
g=cereal['calories']>100
cereal[g]

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.00,1.00,33.983679
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.00,0.75,34.384843
5,Apple Cinnamon Cheerios,G,C,110,2,2,180,1.5,10.5,10,70,25,1,1.00,0.75,29.509541
6,Apple Jacks,K,C,110,2,0,125,1.0,11.0,14,30,25,2,1.00,1.00,33.174094
7,Basic 4,G,C,130,3,2,210,2.0,18.0,8,100,25,3,1.33,0.75,37.038562
10,Cap'n'Crunch,Q,C,120,1,2,220,0.0,12.0,12,35,25,2,1.00,0.75,18.042851
11,Cheerios,G,C,110,6,2,290,2.0,17.0,1,105,25,1,1.00,1.25,50.764999
12,Cinnamon Toast Crunch,G,C,120,1,3,210,0.0,13.0,9,45,25,2,1.00,0.75,19.823573
13,Clusters,G,C,110,3,2,140,2.0,13.0,7,105,25,3,1.00,0.50,40.400208
14,Cocoa Puffs,G,C,110,1,1,180,0.0,12.0,13,55,25,2,1.00,1.00,22.736446
15,Corn Chex,R,C,110,2,0,280,0.0,22.0,3,25,25,1,1.00,1.00,41.445019
17,Corn Pops,K,C,110,1,0,90,1.0,13.0,12,20,25,2,1.00,1.00,35.782791
18,Count Chocula,G,C,110,1,1,180,0.0,12.0,13,65,25,2,1.00,1.00,22.396513
19,Cracklin' Oat Bran,K,C,110,3,3,140,4.0,10.0,7,160,25,3,1.00,0.50,40.448772
21,Crispix,K,C,110,2,0,220,1.0,21.0,3,30,25,3,1.00,1.00,46.895644
24,Froot Loops,K,C,110,2,1,125,1.0,11.0,13,30,25,2,1.00,1.00,32.207582
25,Frosted Flakes,K,C,110,1,0,200,1.0,14.0,11,25,25,1,1.00,0.75,31.435973
27,Fruit & Fibre Dates; Walnuts; and Oats,P,C,120,3,2,160,5.0,12.0,10,200,25,3,1.25,0.67,40.917047
28,Fruitful Bran,K,C,120,3,0,240,5.0,14.0,12,190,25,3,1.33,0.67,41.015492
29,Fruity Pebbles,P,C,110,1,1,135,0.0,13.0,12,25,25,2,1.00,0.75,28.025765
31,Golden Grahams,G,C,110,1,1,280,0.0,15.0,9,45,25,2,1.00,0.75,23.804043
33,Grape-Nuts,P,C,110,3,0,170,3.0,17.0,3,90,25,3,1.00,0.25,53.371007
34,Great Grains Pecan,P,C,120,3,3,75,3.0,13.0,4,100,25,3,1.00,0.33,45.811716
35,Honey Graham Ohs,Q,C,120,1,2,220,1.0,12.0,11,45,25,2,1.00,1.00,21.871292
36,Honey Nut Cheerios,G,C,110,3,1,250,1.5,11.5,10,90,25,1,1.00,0.75,31.072217
37,Honey-comb,P,C,110,1,0,180,0.0,14.0,11,35,25,1,1.00,1.33,28.742414
38,Just Right Crunchy Nuggets,K,C,110,2,1,170,1.0,17.0,6,60,100,3,1.00,1.00,36.523683
39,Just Right Fruit & Nut,K,C,140,3,1,170,2.0,20.0,9,95,100,3,1.30,0.75,36.471512
40,Kix,G,C,110,2,1,260,0.0,21.0,3,40,25,2,1.00,1.50,39.241114
42,Lucky Charms,G,C,110,2,1,180,0.0,12.0,12,55,25,2,1.00,1.00,26.734515
44,Muesli Raisins; Dates; & Almonds,R,C,150,4,3,95,3.0,16.0,11,170,25,3,1.00,1.00,37.136863
45,Muesli Raisins; Peaches; & Pecans,R,C,150,4,3,150,3.0,16.0,11,170,25,3,1.00,1.00,34.139765
46,Mueslix Crispy Blend,K,C,160,3,2,150,3.0,17.0,13,160,25,3,1.50,0.67,30.313351
48,Nut&Honey Crunch,K,C,120,2,1,190,0.0,15.0,9,40,25,2,1.00,0.67,29.924285
49,Nutri-Grain Almond-Raisin,K,C,140,3,2,220,3.0,21.0,7,130,25,3,1.33,0.67,40.692320
51,Oatmeal Raisin Crisp,G,C,130,3,2,170,1.5,13.5,10,120,25,3,1.25,0.50,30.450843
52,Post Nat. Raisin Bran,P,C,120,3,1,200,6.0,11.0,14,260,25,3,1.33,0.67,37.840594
58,Raisin Bran,K,C,120,3,1,210,5.0,14.0,12,240,25,2,1.33,0.75,39.259197
61,Rice Chex,R,C,110,1,0,240,0.0,23.0,2,30,25,1,1.00,1.13,41.998933
62,Rice Krispies,K,C,110,2,0,290,0.0,22.0,3,35,25,1,1.00,1.00,40.560159
66,Smacks,K,C,110,2,1,70,1.0,9.0,15,40,25,2,1.00,0.75,31.230054
67,Special K,K,C,110,6,0,230,1.0,16.0,3,55,25,1,1.00,1.00,53.131324
69,Total Corn Flakes,G,C,110,2,1,200,0.0,21.0,3,35,100,3,1.00,1.00,38.839746
70,Total Raisin Bran,G,C,140,3,1,190,4.0,15.0,14,230,100,3,1.50,1.00,28.592785
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.00,0.75,39.106174
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.00,1.00,27.753301
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.00,0.75,36.187559

In [17]:
# Create a crosstab of the name and vitamins columns
pd.crosstab(index=cereal['name'],columns=cereal['vitamins'])

vitamins                   0    25   100
name
100% Bran                    0    1    0
100% Natural Bran            1    0    0
All-Bran                     0    1    0
All-Bran with Extra Fiber    0    1    0
Almond Delight               0    1    0
...                        ...  ...  ...
Triples                      0    1    0
Trix                         0    1    0
Wheat Chex                   0    1    0
Wheaties                     0    1    0
Wheaties Honey Gold          0    1    0

[77 rows x 3 columns]

In [18]:
# Group columns of the DataFrame by the manufacturer(mfr column) and find the average
cereal.groupby(['mfr','type']).mean()

            calories   protein       fat      sodium     fiber      carbo  \
mfr type
A   H     100.000000  4.000000  1.000000    0.000000  0.000000  16.000000
G   C     111.363636  2.318182  1.363636  200.454545  1.272727  14.727273
K   C     108.695652  2.652174  0.608696  174.782609  2.739130  15.130435
N   C      84.000000  2.800000  0.200000   29.000000  4.600000  15.000000
    H     100.000000  3.000000  0.000000   80.000000  1.000000  21.000000
P   C     108.888889  2.444444  0.888889  146.111111  2.777778  13.222222
Q   C      94.285714  2.285714  1.714286  105.714286  1.142857  11.571429
    H     100.000000  5.000000  2.000000    0.000000  2.700000  -1.000000
R   C     115.000000  2.500000  1.250000  198.125000  1.875000  17.625000

            sugars      potass   vitamins     shelf    weight      cups  \
mfr type
A   H     3.000000   95.000000  25.000000  2.000000  1.000000  1.000000
G   C     7.954545   85.227273  35.227273  2.136364  1.049091  0.875000
K   C     7.565217  103.043478  34.782609  2.347826  1.077826  0.796087
N   C     2.200000  145.000000  10.000000  1.600000  0.966000  0.734000
    H     0.000000   -1.000000   0.000000  2.000000  1.000000  1.000000
P   C     8.777778  113.888889  25.000000  2.444444  1.064444  0.714444
Q   C     6.142857   69.285714  14.285714  2.571429  0.857143  0.845714
    H    -1.000000  110.000000   0.000000  1.000000  1.000000  0.670000
R   C     6.125000   89.250000  25.000000  2.000000  1.000000  0.871250

             rating
mfr type
A   H     54.850917
G   C     34.485852
K   C     44.038462
N   C     68.655517
    H     64.533816
P   C     41.705744
Q   C     41.785647
    H     50.828392
R   C     41.542997

In [19]:
# Get rid of the decimal digits in ratings. #For example: 68.402973 -> 68
cereal['rating'].astype('int8')

0     68
1     33
2     59
3     93
4     34
      ..
72    39
73    27
74    49
75    51
76    36
Name: rating, Length: 77, dtype: int8

In [20]:
# Check for missing values in the dataframe
cereal.isnull()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
73,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
74,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
75,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
76,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [21]:
# Create a \"Safe for consumption\" column with boolean value True
cereal['Safe for consumption']=True
cereal

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,Safe for consumption
0,100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973,True
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679,True
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505,True
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912,True
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3,60,25,3,1.0,0.75,39.106174,True
73,Trix,G,C,110,1,1,140,0.0,13.0,12,25,25,2,1.0,1.00,27.753301,True
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,3,115,25,1,1.0,0.67,49.787445,True
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3,110,25,1,1.0,1.00,51.592193,True
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,8,60,25,1,1.0,0.75,36.187559,True

In [22]:
# Remove the sugars column
del cereal['sugars']
cereal

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,potass,vitamins,shelf,weight,cups,rating,Safe for consumption
0,100% Bran,N,C,70,4,1,130,10.0,5.0,280,25,3,1.0,0.33,68.402973,True
1,100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,135,0,3,1.0,1.00,33.983679,True
2,All-Bran,K,C,70,4,1,260,9.0,7.0,320,25,3,1.0,0.33,59.425505,True
3,All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,330,25,3,1.0,0.50,93.704912,True
4,Almond Delight,R,C,110,2,2,200,1.0,14.0,-1,25,3,1.0,0.75,34.384843,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,60,25,3,1.0,0.75,39.106174,True
73,Trix,G,C,110,1,1,140,0.0,13.0,25,25,2,1.0,1.00,27.753301,True
74,Wheat Chex,R,C,100,3,1,230,3.0,17.0,115,25,1,1.0,0.67,49.787445,True
75,Wheaties,G,C,100,3,1,200,3.0,17.0,110,25,1,1.0,1.00,51.592193,True
76,Wheaties Honey Gold,G,C,110,2,1,200,1.0,16.0,60,25,1,1.0,0.75,36.187559,True

In [23]:
# Shuffle the DataFrame using sample() with the frac parameter set to 1
s_cereal=cereal.sample(frac=1)
s_cereal

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,potass,vitamins,shelf,weight,cups,rating,Safe for consumption
55,Puffed Wheat,Q,C,50,2,0,0,1.0,10.0,50,0,3,0.50,1.00,63.005645,True
52,Post Nat. Raisin Bran,P,C,120,3,1,200,6.0,11.0,260,25,3,1.33,0.67,37.840594,True
23,Double Chex,R,C,100,2,0,190,1.0,18.0,80,25,3,1.00,0.75,44.330856,True
33,Grape-Nuts,P,C,110,3,0,170,3.0,17.0,90,25,3,1.00,0.25,53.371007,True
11,Cheerios,G,C,110,6,2,290,2.0,17.0,105,25,1,1.00,1.25,50.764999,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,Shredded Wheat 'n'Bran,N,C,90,3,0,0,4.0,19.0,140,0,1,1.00,0.67,74.472949,True
69,Total Corn Flakes,G,C,110,2,1,200,0.0,21.0,35,100,3,1.00,1.00,38.839746,True
29,Fruity Pebbles,P,C,110,1,1,135,0.0,13.0,25,25,2,1.00,0.75,28.025765,True
10,Cap'n'Crunch,Q,C,120,1,2,220,0.0,12.0,35,25,2,1.00,0.75,18.042851,True
63,Shredded Wheat,N,C,80,2,0,0,3.0,16.0,95,0,1,0.83,1.00,68.235885,True